### ISSUE TITLE
Eléments structure positions de thèses

### ISSUE THREAD

**Issue by SybilleClochet** [Chartes-TNAH/theses#1]
Bonjour à toutes,

Je viens de créer un label "initialization" pour classer toutes nos issues relatives à notre prise de connaissance du projet, j'espère que le terme vous conviendra, sinon n'hésitez pas à en proposer d'autres.

J'ai effectué un rapide tour d'horizon, en pratiquant la méthode de l'échantillonnage (!) sur les positions de thèses afin de repérer la façon dont elles sont structurées, ceci afin que nous puissions déterminer une structure pour la capitainisation des fichiers et pour l'encodage TEI.

J'ai noté les éléments de structure suivants : Introduction/Sources/Partie n/Chapitre n/Conclusion/Pièces justificatives/Annexes/Edition/Planches.
Avez-vous de votre côté repéré d'autres éléments ?

Je vous souhaite à toutes de bonnes fêtes !
Bien à vous.

**Comment by saroulle** [comment]
Le modèle TEI disponible dans l'onglet Theses mentionne tous les éléments de structure des positions de thèse : http://theses.enc.sorbonne.fr/theses.
