### ISSUE TITLE
Unification des thèses

### ISSUE THREAD

**Issue by AnZadykhina** [Chartes-TNAH/theses#10]
C'est peut-être plutôt la question pour @SybilleClochet et @Verronmere : est-ce qu'on va unifier les types de parties de textes? Les chapitres sont partout mais il y a des variations avec "section" et "partie". Je crois que c'est important pour XPath

**Comment by architexte** [comment]
@AnZadykhina, je viens de faire une proposition dans [position.xml](https://github.com/Chartes-TNAH/theses/blob/master/position.xml)  
La typologie des `div` reste simple (`@type` introduction, part, chapter, etc.)
