### ISSUE TITLE
Fichier CSV avec ppn thèse et IdRef

### ISSUE THREAD

**Issue by AnZadykhina** [Chartes-TNAH/theses#16]
Bonjour! Je n'ai pas trouvé les ppn thèses pour les promos 2006 et 2007.  En plus, comme j'ai déjà dit il y a des difficultés avec quelques auteurs et quelques thèses.  #17

**Comment by vasaura** [comment]
J'ai profité de ton pull request pour corriger une petite erreur de saut de ligne à la ligne 40 qui était déjà présente dans le fichier d'origine. Je ne l'avais pas vu au début. Tes insertions m'ont paru correctes, donc le fichier est à jour.

**Comment by vasaura** [comment]
après avoir validé ton pull request, j'ai réalisé qu'il y avait un problème d'encodage du fichier. je l'ai sauvegardé en utf-8 et j'ai refait un pull request sur ta branche.

**Comment by AnZadykhina** [comment]
Comment as-tu trouvé ce problème? En cliquant le view, je vois pas des erreurs

**Comment by vasaura** [comment]
j'ai vu les erreurs en ouvrant le fichier avec TextWrangler qui utilise par défaut utf-8 et qui du coup a généré les erreurs d'encodage à l'ouverture du fichier.

**Comment by AnZadykhina** [comment]
D'accord, excuse-moi pour cette erreur. Peut-être c'est un problème avec LibreOffice. Merci beaucoup pour ton aide et ta correction

**Comment by vasaura** [comment]
Pas de soucis. D'ailleurs, je ne sais pas d'où vient l'erreur. Je me demande si ce n'était pas moi qui l'ai générée en faisant une mauvaise sauvegarde. 
En revanche, le saut de ligne avait été dans le fichier depuis le début. Je pense qu'il faut qu'on regarde attentivement si cela n'a pas provoqué d'autres décalages au moment de la création des colonnes.
