### ISSUE TITLE
Proposition finale xml

### ISSUE THREAD

**Issue by SybilleClochet** [Chartes-TNAH/theses#21]
@saroulle : à toi de jouer pour le header :)) !
@vasaura @AnZadykhina @Verronmere : l'attribut "n" est sur 3 lettres pour l'intro ("int"), les sources ("src"), la conclusion ("ccl") et les annexes ("apx").
[https://drive.google.com/open?id=1kSKrdePKj5F1AZ7gBzessFxsagMmsnqB]

**Comment by architexte** [comment]
Idéalement, il faudrait suivre au plus près la sémantique proposée dans les [guidelines](http://www.tei-c.org/release/doc/tei-p5-doc/fr/html/DS.html#DSDIV)

**Comment by SybilleClochet** [comment]
@architexte : est-ce le fait que l'attribut type des div intro, sources, conclusion et annexes soit une expression plutôt qu'un chiffre qui vous gêne ? Nous avons vu ce point hier en atelier pour XPath et capitains.

**Comment by saroulle** [comment]
@SybilleClochet 
Peux-tu adapter ta proposition avec cet auteur car l'exemple que tu as utilisé n'est pas dans notre corpus car il dépend de la promo 1999 ? Partons de cet auteur : Chevrant-Breton, Philippe (1972-...), promotion 2000 : https://www.idref.fr/14974983X

**Comment by saroulle** [comment]
J'ai fait un push d'un fichier complet xml avec la nouvelle structure : pos2000pos200010.xml (j'ai oublié le point dans le nommage du fichier, désolée), dans data/pos2000/pos200010/ créée sur la banche issue20 (#20 ).
Le test Travis peut être fait sur ce fichier.

**Comment by AnZadykhina** [comment]
Si je comprends bien, XPath pour nos fichiers doit ressembler à cette modèle, mais je ne peux pas comprendre comment on doit nommer le premier niveau. J'ai choisi "part" mais je ne suis pas sûre que ce nom est correct.
```
<encodingdesc>
    <refsDecl n="CTS">
      <cRefPattern n="chapter"
        matchPattern="(\w+).(\w+)"
        replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@n='$1']/tei:div[@n='$2'])">
        <p>This pointer pattern extracts part and chapter</p>
      </cRefPattern>
      <cRefPattern n="part?"
        matchPattern="(\w+)"
        replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div[@n='$1'])">
        <p>This pointer pattern extracts part</p>
      </cRefPattern>
    </refsDecl>
  </encodingdesc>
```
