### ISSUE TITLE
Corrections des fichiers cts work et tei header suite aux tests Travis

### ISSUE THREAD

**Issue by saroulle** [Chartes-TNAH/theses#26]
Corrections des fichiers cts work et teiHeader  créés automatiquement, suite aux tests Travis.
Résultat des tests :
data/pos2006/pos200604/__cts__.xml
data/pos2006/pos200611/__cts__.xml 
data/pos2010/pos201021/__cts__.xml

**Comment by vasaura** [comment]
@saroulle 
pour le fichier 201021 le problème vient de la balise /num. 
Je précise que le titre apparait 2 fois dans le fichier teiHeader, donc il faut faire la correction 2 fois+ une fois dans le cts. 
Aussi, étant donné que ces informations sont issues du fichier csv, je vous propose de corriger le csv, car c'est le fichier source.

**Comment by AnZadykhina** [comment]
@vasaura Je crois que c'est une très bonne idée. En plus je crois qu'il faut faire la correction de csv pour ces trois titles.

**Comment by saroulle** [comment]
J'ai fait les corrections des balises /num en /abbr dans les fichiers concernés.
@vasaura @AnZadykhina en effet il faut mettre à jour le fichier csv.

**Comment by AnZadykhina** [comment]
@saroulle J'ai fait ces corrections dans nouveau pull request
