### ISSUE TITLE
Body modifié

### ISSUE THREAD

**Issue by AnZadykhina** [Chartes-TNAH/theses#36]
Bonsoir. J'ai modifié les bodys avec XSLT et ils sont prêts pour concaténation avec teiHeader. Il reste seulement une question: quand on va vérifier les fichier? Probablement, il sera mieux de faire la vérification finale après la concaténation.

**Comment by vasaura** [comment]
Oui, d'accord. Je travaille sur la version complète

**Comment by saroulle** [comment]
Bravo @AnZadykhina et @vasaura. Nous attendons les fichiers concaténés pour faire les vérifications.
