### ISSUE TITLE
proposer un modèle pour le teiHeader

### ISSUE THREAD

**Issue by vasaura** [Chartes-TNAH/theses#6]
J'ai ouvert la branche issue#6 avec un modèle xml du teiHeader. il est à débattre.  Un tableau de correspondance entre les champs du fichier csv et les balises tei header. Quelle balise TEI pour quel champs csv.

**Comment by AnZadykhina** [comment]
Salut!

Comme j'ai promis, c'est une petite partie de teiHeader avec XPath

<encodingDesc>
      <refsDecl n="">
        <cRefPattern n="chapter" matchPattern="(\w+).(\w+)"
          replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2'])">
          <p>This pointer pattern extracts Section and Chapter</p>
        </cRefPattern>
        <cRefPattern n="section" matchPattern="(\w+)"
          replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1'])">
          <p>This pointer pattern extracts Section</p>
        </cRefPattern>
      </refsDecl>
    </encodingDesc>

**Comment by AnZadykhina** [comment]
Salut!

Comme j'ai promis: une petite partie de teiHeader avec XPAth

`<encodingDesc>
      <refsDecl n="">
        <cRefPattern n="chapter" matchPattern="(\w+).(\w+)"
          replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2'])">
          <p>This pointer pattern extracts Section and Chapter</p>
        </cRefPattern>
        <cRefPattern n="section" matchPattern="(\w+)"
          replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1'])">
          <p>This pointer pattern extracts Section</p>
        </cRefPattern>
      </refsDecl>
    </encodingDesc>`

**Comment by editions** [comment]
proposition de @vasaura 

```xml
<teiHeader>
      <fileDesc>
         <titleStmt>
            <title type="full">
               <title type="main">Title </title><!-- csv file:Titre -->
               <title type="desc">Position de thèse</title>
            </title>
            <principal>Prenom, Nom </principal><!-- - csv file: Nom, Prénom -->
            <respStmt>
               <resp>responsable du projet de publication</resp>
               <name>Vincent Jolivet</name>
            </respStmt>
         </titleStmt>
         <editionStmt>
            <edition>Edition revisée par les étudiants du Master Technologies Numériques Appliquées
               à l'histoire de l'Ecole des chartes <date>2018</date></edition>
            <respStmt>
               <resp>revision par</resp>
               <name>Ekaterina Batova</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Sybille Clochet</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Sabine Rouleau</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Aurelia Vasile</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Anastasiia Zadykhina</name>
            </respStmt>
         </editionStmt>
         <publicationStmt>
            <publisher> École nationale des chartes </publisher>
            <pubPlace>Paris</pubPlace>
            <address>
               <addrLine>65 rue de Richelieu,75002, Paris</addrLine>
            </address>
            <date when="2018">2018</date>
            <idno>id</idno><!-- fichier csv: ID -->
            <availability>
               <p> Le texte des positions de thèses depuis 2000 est librement et gratuitement
                  consultable sur le site de l'Ecole des chartes.</p>
            </availability>
         </publicationStmt>
         <sourceDesc>
            <p>Document numérique natif, encodée en xml-tei, sans teiHeadear</p><!-- peut-on considérer comme source les positions déja publiées sur le site de l'ecole? -->
         </sourceDesc>
      </fileDesc>
      <encodingDesc>
         <projectDesc>
            <p>Les thèses de l'Ecole des chartes font l'objet de résumés détaillés et rédigés par
               les auteurs, appelés positions de thèses qui donnent lieu, chaque année, à la
               publication d'un recueil par l'École. L'encodage en xml-tei des positions des thèses
               a lieu dans le context de valorisation des ressources électroniques du Campus
               Condorcet</p>
         </projectDesc>
      </encodingDesc>
      <profileDesc>
         <creation>
            La position de thèse est issue d'une thèse soutenue en <date when="2000">2000</date> <!-- fichier csv:Promotion -->
         </creation>
         <textClass>
            <keywords> <term>not before, not after</term></keywords><!-- fichier csv:notBefor, notAfter -->
         </textClass>
         <langUsage>
            <language ident="fr">français</language>
         </langUsage>
      </profileDesc>
      <revisionDesc>
         <change who="Aurelia Vasile" when="2018-01-03">creation du template teiHeader</change>
      </revisionDesc>
</teiHeader>
```

**Comment by saroulle** [comment]
Modification de la proposition de @vasaura 

La structure du teiHeader me convient. J'ai juste corrigé quelques coquilles, harmonisé l'écriture de l’École nationale des chartes. Je me pose des questions concernant la sourceDesc. Ne faut-il pas faire référence à l'édition papier des positions de thèses ? Je pense que les fichiers ont été réalisés à partir de ces éditions.
Concernant les keywords, je pense qu'il faut ajouter "période" avant les dates pour bien préciser que ce sont des dates. Je ne crois pas qu'il soit possible de typer les termes de l'indexation en date. Je n'ai pas trouvé en tous les cas.

<teiHeader>
      <fileDesc>
         <titleStmt>
            <title type="full">
               <title type="main">Title</title>
               <title type="desc">Position de thèse</title>
            </title>
            <principal key="Nom, prénom (AAAA-...)" ref="https://ark...">Prenom Nom</principal>
            <respStmt>-
               <resp>responsable du projet de publication</resp>
               <name>Vincent Jolivet</name>
            </respStmt>
         </titleStmt>
         <editionStmt>
            <edition>Edition revisée par les étudiants du Master Technologies Numériques Appliquées
               à l'histoire de l'Ecole nationale des chartes <date>2018</date></edition>
            <respStmt>
               <resp>revision par</resp>
               <name>Ekaterina Batova</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Sybille Clochet</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Sabine Roulleau</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Aurelia Vasile</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Anastasiia Zadykhina</name>
            </respStmt>
         </editionStmt>
         <publicationStmt>
            <publisher> École nationale des chartes </publisher>
            <pubPlace>Paris</pubPlace>
            <address>
               <addrLine>65 rue de Richelieu</addrLine>
               <addrLine>75002 Paris</addrLine>
            </address>
            <date when="2018">2018</date>
            <idno>id</idno>
            <availability>
               <p>Le texte des positions de thèses depuis 2000 est librement et gratuitement
                  consultable sur le site de l'Ecole nationale des chartes.</p>
            </availability>
         </publicationStmt>
         <sourceDesc>
            <p>Document numérique natif, encodée en xml-tei, sans teiHeadear</p>
            
         </sourceDesc>
      </fileDesc>
      <encodingDesc>
         <projectDesc>
            <p>Les thèses de L’École nationale des chartes font l'objet de résumés détaillés et rédigés par
               les auteurs, appelés positions de thèses qui donnent lieu, chaque année, à la
               publication d'un recueil par l'École. L'encodage en xml-tei des positions des thèses
               a lieu dans le contexte de valorisation des ressources électroniques du Campus
               Condorcet</p>
         </projectDesc>
      </encodingDesc>
      <profileDesc>
         <creation>
            La position de thèse est issue d'une thèse soutenue en <date when="2000">2000</date> 
         </creation>
         <textClass>
            <keywords> <term>not before, not after</term></keywords>
            
         </textClass>
         <langUsage>
            <language ident="fr">français</language>
         </langUsage>
      </profileDesc>
      <revisionDesc>
         <change who="Aurelia Vasile" when="2018-01-03">creation du template teiHeader</change>
      </revisionDesc>
</teiHeader>

**Comment by editions** [comment]
Pour le `titleStmt` : proposition

```xml
<titleStmt>
  <title type="main">Titre</title><!-- csv file:Titre -->
  <title type="sub">Sous-Titre</title><!-- csv file:Titre -->
  <author key="@authorKey" ref="URI-idRef">Prénom Nom</author><!-- - csv file: Nom, Prénom.
</titleStmt>
```

* `<title type="desc">Position de thèse</title>` : voir `seriesStmt`
* `respStmt`sur édition et non sur mentions de titre…
* que fait-on des ppn_position et ppn_these ? – voir `sourceDesc`, faire une proposition.

**Comment by saroulle** [comment]
@architexte : Nouvelle proposition de teiHeader avec un titleStmt et un sourceDesc différents suite à la réunion du 24/01/2018.

``` xml
<teiHeader>
      <fileDesc>
         <titleStmt>            
                  <title type="main">Titre</title><!-- csv file:Titre -->
                  <title type="sub">Sous-Titre</title><!-- csv file:Titre -->
                  <author key="@authorKey" ref="URI-idRef">Prénom Nom</author><!-- - csv file: Nom, Prénom. -->                  
            <respStmt>-
               <resp>responsable du projet de publication</resp>
               <name>Vincent Jolivet</name>
            </respStmt>
         </titleStmt>
         <editionStmt>
            <edition>Edition revisée par les étudiants du Master Technologies Numériques Appliquées
               à l'histoire de l'Ecole nationale des chartes <date>2018</date></edition>
            <respStmt>
               <resp>revision par</resp>
               <name>Ekaterina Batova</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Sybille Clochet</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Sabine Roulleau</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Aurelia Vasile</name>
            </respStmt>
            <respStmt>
               <resp>revision par</resp>
               <name>Anastasiia Zadykhina</name>
            </respStmt>
         </editionStmt>
         <publicationStmt>
            <publisher> École nationale des chartes </publisher>
            <pubPlace>Paris</pubPlace>
            <address>
               <addrLine>65 rue de Richelieu</addrLine>
               <addrLine>75002 Paris</addrLine>
            </address>
            <date when="2018">2018</date>         
            <availability>
               <p>Le texte des positions de thèses depuis 2000 est librement et gratuitement
                  consultable sur le site de l'Ecole nationale des chartes.</p>
            </availability>
         </publicationStmt>
         <sourceDesc>
            <seriesStmt xml:lang="fre">
               <title level="s" source="SUDOC" ref="http://www.sudoc.fr/013565311">Positions des thèses</title>  
               <respStmt>
                  <name type="org">École nationale des chartes (Paris)</name>
               </respStmt>
               <date from="1848">1848-</date>
               <idno type="issn">0755-2076</idno>                
               <biblScope unit="annee">AAAA</biblScope> <!-- csv file : promotion -->
               <title type="a" id="id">titre</title> <!-- csv file:Titre + id position-->
               </seriesStmt>
               <monogr>
                  <title source="SUDOC" ref="http://www.sudoc.fr/167764489">titre</title> <!-- csv file:Titre -->
               </monogr>
         </sourceDesc>
      </fileDesc>
      <encodingDesc>
         <projectDesc>
            <p>Les thèses de l'Ecole nationale des chartes font l'objet de résumés détaillés et rédigés par
               les auteurs, appelés positions de thèses qui donnent lieu, chaque année, à la
               publication d'un recueil par l'École. L'encodage en xml-tei des positions des thèses
               a lieu dans le contexte de valorisation des ressources électroniques du Campus
               Condorcet</p>
         </projectDesc>
      </encodingDesc>
      <profileDesc>
         <creation>
            La position de thèse est issue d'une thèse soutenue en <date when="2000">2000</date> <!-- fichier csv:Promotion -->
         </creation>
         <textClass>
            <keywords> <term>not before, not after</term></keywords><!-- fichier csv:notBefor, notAfter -->
            <!--je rajouterais un élément pour préciser que c'est une période car il y a des 0 dans le champ notbefor 
               et j'ai peur que ça ne soit pas très explicite. Je n'ai pas trouvé d'éléments dans les 
               guidelines pour préciser que c'était des dates -->
         </textClass>
         <langUsage>
            <language ident="fr">français</language>
         </langUsage>
      </profileDesc>
      <revisionDesc>
         <change who="Aurelia Vasile" when="2018-01-03">creation du template teiHeader</change>
         <change who="Sabine Roulleau" when="2018-01-29">ajout d'élément au niveau du sourceDesc du template teiHeader</change>
      </revisionDesc>
</teiHeader>   
```

**Comment by architexte** [comment]
Proposition, plus ramassée, voir [position.xml](https://github.com/Chartes-TNAH/theses/blob/master/position.xml)  
Il faut insérer le nécessaire pour capitainiser…
```xml
<teiHeader>
    <fileDesc>
      <titleStmt>
        <title type="main">Politique lignagère et ambitions comtales en Lorraine</title>
        <title type="sub">La famille et la seigneurie d’Apremont des origines au début du <hi rend="sc">xiv</hi><hi rend="sup">e</hi> siècle</title>
        <author key="Auclair, Mathias" ref="https://www.idref.fr/092771327">Mathias Auclair</author>
      </titleStmt>
      <editionStmt>
        <edition>École des chartes</edition>
      </editionStmt>
      <publicationStmt>
        <publisher>École des chartes</publisher>
        <date when="2018"/>
        <availability status="restricted">
          <licence target="http://creativecommons.org/licenses/by-nc-nd/3.0/fr/"/>
        </availability>
      </publicationStmt>
      <seriesStmt>
        <title>Positions des thèses</title>
        <idno type="ISSN">0755-2976</idno>
        <idno type="URI">http://www.sudoc.fr/013565311</idno>
      </seriesStmt>
      <sourceDesc>
        <bibl><title>Positions des thèses soutenues par les élèves de la promotion de 1999 pour obtenir le diplôme d’archiviste paléographe</title>, <pubPlace>Paris</pubPlace>, <publisher>École des chartes</publisher>, <date>1999</date>, <biblScope unit="page" from="33" to="43">33-43</biblScope>.</bibl>
      </sourceDesc>
    </fileDesc>
    <profileDesc>
      <creation>
        <date when="1999"/>
      </creation>
      <langUsage>
        <language ident="fr"/>
      </langUsage>
    </profileDesc>
  </teiHeader>
```

**Comment by saroulle** [comment]
Proposition de métadonnées pour Capitains, en structurant les fichiers par année de promotion (soit un textgroup par promotion). 

``` xml
 <ti:textgroup urn="urn:cts:theses:pos_2000"
      xmlns:cpt="http://purl.org/capitains/ns/1.0#"
      xmlns:dc="http://purl.org/dc/elements/1.1/"
      xmlns:dct="http://purl.org/dc/terms/"
      xmlns:ti="http://chs.harvard.edu/xmlns/cts">
   <ti:groupname>Positions de thèses de l'Ecole des Chartes promotion 2000</ti:groupname>
      <ti:work groupUrn="urn:cts:theses:pos_2000" xml:lang="fre" urn="urn:cts:theses:pos_2000.200001">
         <ti:title xml:lang="fre">Du moujik à l’artiste. L’Académie impériale des Beaux-arts de Saint-Pétersbourg (1757-1802)</ti:title>
         <ti:description xml:lang="fre">Position de thèse de Basile Baudez, promotion 2000</ti:description>
            <cpt:structured-metadata>
               <dc:creator xml:lang="fre">Basile Baudez</dc:creator>
               <dc:title xml:lang="fre">Du moujik à l’artiste. L’Académie impériale des Beaux-arts de Saint-Pétersbourg (1757-1802)</dc:title>      
               <dc:publisher xml:lang="fre">Ecole nationale des Chartes</dc:publisher>
               <dct:dateCopyrighted rdf:datatype="xsd:gYear">2000</dct:dateCopyrighted>
            </cpt:structured-metadata>
      </ti:work>
   </ti:textgroup>
```

**Comment by AnZadykhina** [comment]
Pourquoi les donnés sur l'auteur et le nom de thèse sont ici? Je crois qu'ils doivent être dans le fichier cts pour work.
