### ISSUE TITLE
Proposition de modèle body TEI

### ISSUE THREAD

**Issue by Verronmere** [Chartes-TNAH/theses#7]
Je propose un modèle de body où j'ai intégré le front et le back dans ce fameux body. La question suivante - faut-il vraiment intégrer l'untitulé (le nom de l'auteur et le nom de la thèse) en body?

**Comment by AnZadykhina** [comment]
Je crois que ces noms doivent rester seulement en header

**Comment by SybilleClochet** [comment]
Bonjour Ekaterina, bonjour à toutes,

je fais le même constat qu'Ekaterina, comme évoqué hier : soit ces éléments restent dans un front, soit ils migrent dans le TEI header (évoqué avec Sabine et Aurelia). Sans doute devrons-nous interroger M. Jolivet sur ce point. Dans l'intervalle, nous pouvons faire deux propositions ?

**Comment by AnZadykhina** [comment]
Bonjour Sybille! Je crois qu'on ne peut pas garder le front et back à cause de XPath et de CaPiTaiNs. En plus, en travaillant un peu avec notre fichier, j'ai collé ces schémas <?xml version="1.0" encoding="UTF-8"?><?xml-model href="http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<TEI xml:lang="fr" xmlns="http://www.tei-c.org/ns/1.0"> (je ne me rappele pas vraiment ou j'ai trové ça) mais ces schemas ne permettent pas d'utiliser front et back

**Comment by SybilleClochet** [comment]
Bonjour Anastasiia,

bien noté alors, nous supprimons complètement le front et faisons avec header + body seuls.
Bien à toi,
sybille

**Comment by SybilleClochet** [comment]
Bonsoir à toutes,

Une première proposition de spécifications pour tei>body ci-dessous.

Bonne fin de soirée.
Sybille


[prop_body_tei.txt](https://github.com/Chartes-TNAH/theses/files/1636992/prop_body_tei.txt)

**Comment by Verronmere** [comment]
Si c'est beaucoup plus pratique d'avoir un fichier comme ça,

Je propose une sorte de version intégrée.  J'ai ajouté quelques conteineers de plus.

Un pour englober la thèse entière
Un pour l'ancien front, body et back.
Pour se réperer parmi les conteineers on pourrait utiliser des id, mais plus faciles et intuitifs... ou rester avec des types ou des n.

[modelBODYv2.docx](https://github.com/Chartes-TNAH/theses/files/1639392/modelBODYv2.docx)
 
`<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml"
	schematypens="http://purl.oclc.org/dsdl/schematron"?>

<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        
        <title>
          Japonisme et érudition : le livre japonais dans les collections d’Auguste Lesouëf (1829-1906)
        </title>
        <author>
          Véronique BÉRANGER
        </author>
      </titleStmt>
      <publicationStmt>
        <p>
        </p>
      </publicationStmt>
      <sourceDesc>
        <p>
          
        </p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text xml:lang="fr">
    <body>
      <div xml:id="these">   
        <div xml:id="front"> 
          <div xml:id="intro">
             <head>Introduction</head>
             <p>texte</p>
          </div>
          <div xml:id="sources">
             <head>Sources</head>
             <p>texte</p>
          </div>
        </div>
        <div xml:id="body">  
          <div xml:id="PT01" type="part" n="1">
             <head n="Partie I">Titre de la partie</head>
             <div xml:id="PT0101" type="chapter" n="1">
               <head n="Chapitre I">Titre du chapitre</head>
               <p>text</p>
             </div>
             <div xml:id="PT0102" type="chapter" n="2">
               <head n="Chapitre II">Titre du chapitre</head>
               <p>...</p>
             </div>
             <div xml:id="PT0103" type="chapter" n="3">
               <head n=" Chapitre III">Titre du chapitre</head>
               <p>...</p>
             </div>
           </div>
           <div xml:id="PT02" type="part" n="2">
              <head n="Partie II">Titre de la partie</head>
              <div xml:id="PT0201" type="chapter" n="1">
                <head n="Chapitre I">Titre du chapitre</head>
                <p>text</p>
              </div>
              <div xml:id="PT0202" type="chapter" n="2">
                <head n="Chapitre II">Titre du chapitre</head>
                <p>...</p>
              </div>
              <div xml:id="PT0203" type="chapter" n="3">
                <head n=" Chapitre III">Titre du chapitre</head>
                <p>...</p>
              </div>
            </div>
            <div xml:id="PT03" type="part" n="3">
              <head n="Partie II">Titre de la partie</head>
              <div xml:id="PT0301" type="chapter" n="1">
                <head n="Chapitre I">Titre du chapitre</head>
                <p>text</p>
              </div>
              <div xml:id="PT0302" type="chapter" n="2">
                <head n="Chapitre II">Titre du chapitre</head>
                <p>...</p>
              </div>
              <div xml:id="PT0303" type="chapter" n="3">
                <head n=" Chapitre III">Titre du chapitre</head>
                <p>...</p>
              </div>
            </div>
          </div>
          <div xml:id="back">  
            <div xml:id="conclusion">
              <head>Conclusion</head>
              <p>...</p>
            </div>
            <div xml:id="justification">
              <head>Pièces justificatives</head>
              <p>...</p>
            </div>
            <div xml:id="annexes">
              <head>Annexes</head>
              <p>...</p>
            </div>
            <div xml:id="planches">
              <head>Planches</head>
              <p>...</p>
            </div>
          </div>
      </div>
    </body>
  </text>
</TEI>`

**Comment by SybilleClochet** [comment]
Bonjour à toutes,
pour faire suite à la réunion de mercredi avec M. Jolivet et reprenant nos réflexions sur les div, je vous envoie la proposition ci-dessous. J'ai tourné le truc sans résoudre le problème de la succession de <div> (je ne vois vraiment pas comment faire) et j'ai "sectionné" les positions en 3 blocs qui constituent 3 @type de <div> : type="front" (pour intro et sources), type="core" pour les parties et chapitres, type="back" qui englobe deux types lui-même (un type="conclusion" pour la conclusion" et un type="optional" qui englobe tout les parties optionnelles).
Qu'en pensez-vous ? @AnZadykhina : cela te semble-t-il conforme pour Xpath ?
Bien à vous,
sybille
-------------
<text>
	<body>
<div type="front">
          <div type="introduction">
             <head>Introduction</head>
             <p>texte</p>
          </div>
          <div type="sources">
             <head>Sources</head>
             <p>texte</p>
          </div>
</div>
<div type="core">
          <div type="part" n="1">
             <head>Titre de la partie</head>
             <div type="chapter" n="1">
               <head>Titre du chapitre</head>
               <p>text</p>
             </div>
             <div type="chapter" n="2">
               <head>Titre du chapitre</head>
               <p>...</p>
             </div>
             <div type="chapter" n="3">
               <head>Titre du chapitre</head>
               <p>...</p>
             </div>
           </div>
           <div type="part" n="2">
              <head>Titre de la partie</head>
              <div type="chapter" n="1">
                <head>Titre du chapitre</head>
                <p>text</p>
              </div>
              <div type="chapter" n="2">
                <head>Titre du chapitre</head>
                <p>...</p>
              </div>
              <div type="chapter" n="3">
                <head>Titre du chapitre</head>
                <p>...</p>
              </div>
            </div>
            <div type="part" n="3">
              <head>Titre de la partie</head>
              <div type="chapter" n="1">
                <head>Titre du chapitre</head>
                <p>text</p>
              </div>
              <div type="chapter" n="2">
                <head>Titre du chapitre</head>
                <p>...</p>
              </div>
              <div type="chapter" n="3">
                <head>Titre du chapitre</head>
                <p>...</p>
              </div>
            </div>
          </div>
          <div type="back">
<div type="conclusion">
              <head>Conclusion</head>
              <p>...</p>
            </div>
           <div type="optional">
              <head>Pièces justificatives</head>
              <p>...</p>
</div>
           <div type="optional">
              <head>Annexes</head>
              <p>...</p>
            </div>
  	<div type="optional">
              <head>Planches</head>
              <p>...</p>
            </div>
          </div>
    </body>
  </text>
</TEI>

**Comment by SybilleClochet** [comment]
Bonjour à toutes,
pour faire suite à la réunion de mercredi avec M. Jolivet et reprenant nos réflexions sur les div, je vous envoie la proposition ci-dessous. J'ai tourné le truc sans résoudre le problème de la succession de
(je ne vois vraiment pas comment faire) et j'ai "sectionné" les positions en 3 blocs qui constituent 3 @type de
: type="front" (pour intro et sources), type="core" pour les parties et chapitres, type="back" qui englobe deux types lui-même (un type="conclusion" pour la conclusion" et un type="optional" qui englobe tout les parties optionnelles).
Qu'en pensez-vous ? @AnZadykhina : cela te semble-t-il conforme pour Xpath ?
P.S. : je suis au boulot :)) donc je n'ai pas oxygen, alors je vous transmets un fichier txt...
[Propal2_body.txt](https://github.com/Chartes-TNAH/theses/files/1667975/Propal2_body.txt)

Bien à vous,
sybille

**Comment by SybilleClochet** [comment]
Chères toutes,
Après relecture des spéc. de Capitains, il me semble que la proposition ci-jointe pourrait convenir : pour "couvrir" les éléments de structure, je me suis servie de l'élément <milestone>.
cf. ci-joint.
```XML`
<?xml version="1.0" encoding="UTF-8"?>
<tei>
    <teiheader> </teiheader>
    <body>
        <text>
            <milestone unit="section" n="1">
                <div type="introduction">
                    <head>Introduction</head>
                </div>
                <div type="sources">
                    <head>Sources</head>
                </div>
            </milestone>
            <milestone unit="part" n="1">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </milestone>
            <milestone unit="part" n="2">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </milestone>
            <milestone unit="part" n="3">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </milestone>
            <milestone unit="section" n="2">
                <div type="conclusion">
                    <head>Conclusion</head>
                </div>
            </milestone>
            <milestone unit="section" n="3">
                <div type="optional" n="1">
                    <head>Pièces justificatives</head>
                </div>
            </milestone>
        </text>
    </body>
</tei>

**Comment by SybilleClochet** [comment]
Après relecture des spécs de Capitains, voici une nouvelle proposition qui me semble conforme, avec l'élément milestone qui permet de "couvrir" les grandes sections de structuration des positions.

bien à vous,
sybille
```<?xml version="1.0" encoding="UTF-8"?>
<tei>
    <teiheader> </teiheader>
    <body>
        <text>
            <milestone unit="section" n="1">
                <div type="introduction">
                    <head>Introduction</head>
                </div>
                <div type="sources">
                    <head>Sources</head>
                </div>
            </milestone>
            <milestone unit="part" n="1">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </milestone>
            <milestone unit="part" n="2">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </milestone>
            <milestone unit="part" n="3">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </milestone>
            <milestone unit="section" n="2">
                <div type="conclusion">
                    <head>Conclusion</head>
                </div>
            </milestone>
            <milestone unit="section" n="3">
                <div type="optional" n="1">
                    <head>Pièces justificatives</head>
                </div>
            </milestone>
        </text>
    </body>
</tei>
```

**Comment by PonteIneptique** [comment]
Attention ! `<milestone />` ne peut pas être utilisée en encapsulateur, *ie* `<milestone>quelquechose</milestone>` est interdit par la TEI. Préférez `<div />`

**Comment by SybilleClochet** [comment]
@PonteIneptique : ref email du 20/01, 14h : et est-ce que <milestone/> pourrait convenir ?

**Comment by SybilleClochet** [comment]
@PonteIneptique : ref email du 20/01, 14h : et est-ce que ```<milestone/>``` pourrait convenir ?

**Comment by PonteIneptique** [comment]
@SybilleClochet Je ne vois malheureusement pas de quel mail vous parlez

**Comment by PonteIneptique** [comment]
Cela dit, si je comprends la question, non, `<mileston />` étant non encapsulant, il ne peut pas être utilisé par CapiTainS. Par ailleurs en TEI, `<milestone />` est utilisé pour signifier des systèmes alternatifs au principal alors qu'ici, vous souhaitez indiquer le principal.

**Comment by SybilleClochet** [comment]
@PonteIneptique : pardon, j'avais cru lire dans l'article que vous nous aviez transmis que c'était possible !
@Verronmere @AnZadykhina @saroulle @vasaura ```<?xml version="1.0" encoding="UTF-8"?>
<tei>
    <teiheader> </teiheader>
    <body>
        <text>
                <div type="section" n="1">
                    <head>Introduction</head>
                </div>
                <div type="section" n="2">
                    <head>Sources</head>
                </div>
            
            <div type="part" n="1">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="part" n="2">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="part" n="3">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="section" n="3">
                    <head>Conclusion</head>                
            </div>
            <div type="section" n="4">
                    <head>Pièces justificatives</head>
                <p></p>
                <head>Planches</head>
                
            </div>
        </text>
    </body>
```

**Comment by SybilleClochet** [comment]
@PonteIneptique : pardon, j'avais cru lire dans l'article que vous nous aviez transmis que c'était possible !
@Verronmere @AnZadykhina @saroulle @vasaura ```<tei>
    <teiheader> </teiheader>
    <body>
        <text>
                <div type="section" n="1">
                    <head>Introduction</head>
                </div>
                <div type="section" n="2">
                    <head>Sources</head>
                </div>
            
            <div type="part" n="1">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="part" n="2">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="part" n="3">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="section" n="3">
                    <head>Conclusion</head>                
            </div>
            <div type="section" n="4">
                    <head>Pièces justificatives</head>
                <p></p>
                <head>Planches</head>
                
            </div>
        </text>
    </body>
</tei>```

**Comment by SybilleClochet** [comment]
```XML <tei>
    <teiheader> </teiheader>
    <body>
        <text>
                <div type="section" n="1">
                    <head>Introduction</head>
                </div>
                <div type="section" n="2">
                    <head>Sources</head>
                </div>
            
            <div type="part" n="1">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="part" n="2">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="part" n="3">
                <div type="chapter" n="1">
                    <head>Chapitre 1</head>
                </div>
                <div type="chapter" n="2">
                    <head>Chapitre 2</head>
                </div>
                <div type="chapter" n="3">
                    <head>Chapitre 3</head>
                </div>
            </div>
            <div type="section" n="3">
                    <head>Conclusion</head>                
            </div>
            <div type="section" n="4">
                    <head>Pièces justificatives</head>
                <p></p>
                <head>Planches</head>
                <!-- un head pour chaque type d'annexes -->
            </div>
        </text>
    </body>
</tei>```

**Comment by SybilleClochet** [comment]
@PonteIneptique : pourriez-vous nous dire si notre compréhension est la bonne : la valeur de l'attribut "n" (book, section, part, chapter) de la balise "cRefPattern" a sa correspondance dans l'attribut "type" de la balise "div" (pour notre corpus), dans les fichiers tei des positions. La valeur de l'attribut "type" de la balise "div" étant libre, pouvez-vous nous confirmer que l'attribut "n" peut donc avoir d'autres valeurs que celles citées (book, section...) ?

**Comment by SybilleClochet** [comment]
@architexte @MrGecko : vous touverez ci-dessous notre proposition de body pour les positions, qui suit la proposition déjà formulée pour le teiHeader #6. Dès que nous aurons votre retour, nous reviendrons vers vous pour avoir plus d'informations avant d'attaquer le RelaxNG.
``` XML <?xml version="1.0" encoding="UTF-8"?>
<tei>
    <teiheader> </teiheader>
    <body>
        <text>
                <div type="section" n="1">
                    <head>Introduction</head>
                    <p></p>                   
                    <head>Sources</head>
                    <p></p> 
                </div>
                <div type="section" n="2">            
                    <div type="part" n="1">
                        <head>Première partie</head>
                            <div type="chapter" n="1">
                                <head>Chapitre 1</head>
                                <p></p>
                            </div>
                            <div type="chapter" n="2">
                                <head>Chapitre 2</head>
                                <p></p>
                            </div>
                            <div type="chapter" n="3">
                                <head>Chapitre 3</head>
                                <p></p> 
                            </div>
                    </div>
                    <div type="part" n="2">
                        <head>Deuxième partie</head>
                            <div type="chapter" n="1">
                                <head>Chapitre 1</head>
                                <p></p> 
                            </div>
                            <div type="chapter" n="2">
                                <head>Chapitre 2</head>
                                <p></p> 
                            </div>
                            <div type="chapter" n="3">
                                <head>Chapitre 3</head>
                                <p></p> 
                            </div>
                    </div>
                    <div type="part" n="3">
                        <head>Troisième partie</head>
                            <div type="chapter" n="1">
                                <head>Chapitre 1</head>
                                <p></p> 
                            </div>
                            <div type="chapter" n="2">
                                <head>Chapitre 2</head>
                                <p></p> 
                            </div>
                            <div type="chapter" n="3">
                                <head>Chapitre 3</head>
                                <p></p> 
                            </div>
                     </div>
            </div>
            <div type="section" n="3">
                    <head>Conclusion</head>                
                        <p></p>
                    <head>Pièces justificatives</head>
                        <p></p>
                    <head>Planches</head>
                        <p></p> 
                <!-- un head pour chaque type d'annexes -->
            </div>
        </text>
    </body>
</tei>
```

**Comment by MrGecko** [comment]
@SybilleClochet Cette hiérarchie me paraît correspondre au besoin de découpage attendu. Pouvez-vous mettre à jour la partie <refsDecl n="CTS"></refsDecl> du <teiHeader> correspondant à cette structure ?

**Comment by SybilleClochet** [comment]
@MrGecko : il manque un mot :)) Parlez-vous du schéma en RelaxNG ?

**Comment by architexte** [comment]
Pour le body, proposition : [position.xml](https://github.com/Chartes-TNAH/theses/blob/master/position.xml)

**Comment by SybilleClochet** [comment]
@architexte @PonteIneptique @MrGecko 
@architexte : merci pour votre proposition. Mais elle pose un problème particulier pour Capitains :  l'absence de hiérarchie au-dessus des div "intro" et "sources", "conclusion" et "appendix" nous empêche d'adresser ces éléments et ne rend possible la citation que des éléments "part" et "chapter".

**Comment by SybilleClochet** [comment]
Pardon, suis allée trop vite. Je ferme cette issue qui est désormais à suivre dans #21
