### ISSUE TITLE
structure des fichiers et des repertoires:capitanisation

### ISSUE THREAD

**Issue by vasaura** [Chartes-TNAH/theses#8]
proposer un modèle de structure des fichiers et des repertoires dans le cadre de la capitanisation: dans la branch#8

**Comment by AnZadykhina** [comment]
Je peux proposer la structure mais avant j'aimerais discuter sur la structure de body et sur les ids pour faire pull request avec une version plus ou moins correcte

**Comment by vasaura** [comment]
J'ai voulu dire "un modèle de structuration/organisation des dossiers et des fichiers dans le cadre de la capitanisation" pas le modèle des fichiers (métadonnées) capitaines. 
Pour cela, il est vrai qu'on a besoin d'établir d'abord la structure du fichier tei.

**Comment by AnZadykhina** [comment]
Excuses-moi s'il peut plaît, j'ai pas bien compris. Comme j'ai déjà dit aujourd'hui, j'ai essayé de trouver une option pour ne pas créer DATA pour chaque auteur, mais je n'ai pas trouver la solution. Peut-être tu as quelques idées?

**Comment by vasaura** [comment]
regarde la branch#8, il y a une proposition de structuration. A voir si cela peut convenir

**Comment by AnZadykhina** [comment]
J'ai vu ton document. Tu as raison. C'est ma faute. Je crois qu'on peut créer plusieurs textgroup dans le dossier DATA, mais textgroup sera unique pour chaque auteur

**Comment by AnZadykhina** [comment]
Mais peut-être on va prendre comme le corpus chaque promo?

**Comment by vasaura** [comment]
Proposition de structure pour les fichiers et des repertoires dans le cadre de la capitanisation pour des fichiers et dossiers du corpus theses
[structure capitaines These.pptx](https://github.com/Chartes-TNAH/theses/files/1639399/structure.capitaines.These.pptx)

**Comment by saroulle** [comment]
Il est important de garder un niveau textgroup pour chaque auteur afin d'avoir des fichiers __cts __ des auteurs avec des métadonnées dans capitains.

**Comment by vasaura** [comment]
@PonteIneptique  @architexte 
Voici une nouvelle proposition pour la structuration des répertoires et des fichiers thèses dans le cadre de la capitanisation. Le "textgroup" est organisé par promotion (avec la syntaxe "pos_année"). Les noms des répertoires et des fichiers sont repris depuis le fichier csv. 
[structure capitaines These2.pdf](https://github.com/Chartes-TNAH/theses/files/1682254/structure.capitaines.These2.pdf)

**Comment by vasaura** [comment]
Nous avons jusqu'à maintenant 2 versions de la structuration des répertoires (par auteurs et par année. cf les deux fichiers pdf attachés ci-haut). Les deux ont des avantages et des désavantages: 
- Si on regroupe par auteur, on garde l'identité de l'auteur dans les fichiers cts; 
- Si on regroupe par promotion cela fait plus sens, car les auteurs n'ont qu'une oeuvre, mais dans ce deuxième cas, le nom des fichiers tei est assez peu parlant : pos_2001.200101.xml. 

Le choix à faire est important pour la suite des travaux, car le nom des urn et la structure des cts dépend de cette structuration et nommage. 
Qu'en pensez-vous? Quel choix faire? Est-ce que je me suis trompée dans ces reflexions? Nous avons besoin d'une validation, car on est bloqué.

**Comment by architexte** [comment]
Je me permets de lier @MrGecko puisqu’il a avancé sur ce point – il pourra vous conseiller utilement.
